### ISSUE TITLE
remote_control() function  times out because rc has no response by design

### ISSUE THREAD

**Issue by hhackbarth** [robagar/tello-asyncio#10]
The function remote_control(...) runs into a timeout because rc (accoding to the SDK doc) does not generate a response.

After that, the framwork seems to be in an erratic state because every other command sent afterwards picks up and shows the response but some seconds later you still get a timeout error. Python program must be completely exited and started from scratch in order to comeback to a normal communication.

You can easily test this with the example "interactive_command.py".

**Comment by robagar** [comment]
should be fixed now in 2.1.2
