### ISSUE TITLE
on 'stop' function call drone aborts instead of interrupting movement and hover

### ISSUE THREAD

**Issue by lifeisgood-ai** [robagar/tello-asyncio#13]
Hi

I want to interrupt a drone move using the 'stop' command ( await tello.stop() ) but it raises an error instead of "Stop moving and hover immediately." as the Tello SDK suggests.

I tried a quick fix modifying line 73 of main/tello_asyncio/tello.py from:

>                     if message == 'ok':

to:

>                     if message == 'ok' or message == 'forced stop':

It is not fully working and I am not sure it complies with the rest of the code

**Comment by robagar** [comment]
finally fixed in 2.1.3
